### ISSUE TITLE
Search by query option

### ISSUE THREAD

**Issue by vishal-kony** [muffinista/really-simple-history-api#1]
Do you provide any provision for searching by query?
ex:
_base_url_/query=India 

and we get all the events, births and deaths related to the query?

**Comment by muffinista** [comment]
Sorry, but no. This API works on flat-files and is way to simple to do what you are asking.

**Comment by vishal-kony** [comment]
Thanks for your response. Yep, it is easy. Just wanted to know if it was available. I'll Use as required :) 
Thanks
