### ISSUE TITLE
Empty response for /date

### ISSUE THREAD

**Issue by SherDG** [muffinista/really-simple-history-api#30]
Request

`curl 'https://history.muffinlabs.com/date' \
  -H 'authority: history.muffinlabs.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6' \
  -H 'cache-control: max-age=0' \
  -H 'if-modified-since: Fri, 06 Sep 2024 12:41:41 GMT' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  --compressed`
  
  Response
  `{
  "date": "September 20",
  "url": "https://wikipedia.org/wiki/September_20",
  "data": {
  }
}`

Same issue for request format - https://history.muffinlabs.com/date/2/14

**Comment by muffinista** [comment]
Thanks for pointing it out! Should be fixed now

**Comment by SherDG** [comment]
Works fine. Thanks for a cool and useful API.
![image](https://github.com/user-attachments/assets/5c600c7e-ffb7-4370-822b-74168e4f5cfb)
