### ISSUE TITLE
API endpoint /date is broken

### ISSUE THREAD

**Issue by AndyTheNerd** [muffinista/really-simple-history-api#5]
Hello! I use this awesome API for a Discord bot and noticed the endpoint /date is broken. Heading to this endpoint for "today" does not work, but you can still search for a specific date. 

![image](https://user-images.githubusercontent.com/30298320/107791585-1f841e80-6d22-11eb-95e5-d8732e578412.png)

**Comment by muffinista** [comment]
Oh no! Thanks for letting me know, it should be fixed now.

**Comment by AndyTheNerd** [comment]
Thank you for fixing it! :)
