### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by chevtek** [muffinista/really-simple-history-api#8]
Not a huge deal and I may just take this source and see if I can't host it myself, but thought I'd let you know [your api](http://history.muffinlabs.com/today) is down. Been using it to power a "This day in history" bot in our discord.

![image](https://user-images.githubusercontent.com/874394/133283980-49ff2c23-fde0-479a-a563-20df012bdfe0.png)

Anyway, hope you're doing well! Keep up the good work :)

**Comment by muffinista** [comment]
Thanks for letting me know! It should be back up now.
